apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  # Замените на реальные значения или используйте --from-literal при создании
   username: "admin"
   password: "admin"

